// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "Shaders/GlossyClearCoat.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "PixelShaderUtils.h"
#include "DataDrivenShaderPlatformInfo.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FGlossyClearCoatShader, "/Plugin/Materialize/GlossyClearCoat.usf", "GlossyClearCoatPS", SF_Pixel);

bool FGlossyClearCoatShader::ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
{
    return FDataDrivenShaderPlatformInfo::GetMaxFeatureLevel(Parameters.Platform) >= ERHIFeatureLevel::SM5;
}

void FGlossyClearCoatShader::Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters)
{
    if (!OutputTexture)
    {
        return;
    }

    TShaderMapRef<FGlossyClearCoatShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

    FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
    *PassParameters = Parameters;
    PassParameters->RenderTargets[0] = FRenderTargetBinding(OutputTexture, ERenderTargetLoadAction::ENoAction);

    const FIntRect OutputRect(FIntPoint::ZeroValue, OutputTexture->Desc.Extent);
    FPixelShaderUtils::AddFullscreenPass(
        GraphBuilder,
        GetGlobalShaderMap(GMaxRHIFeatureLevel),
        RDG_EVENT_NAME("Materialize.GlossyClearCoat"),
        PixelShader,
        PassParameters,
        OutputRect);
}

// Helper function to add pass to render graph
void AddPass_GlossyClearCoat(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    float coat_ior,
    FVector3f coat_tint,
    float coat_intensity
)
{
    if (!OutputTexture)
    {
        return;
    }

    FGlossyClearCoatShader::FParameters* Params = GraphBuilder.AllocParameters<FGlossyClearCoatShader::FParameters>();
    // Bind Scalars
    Params->coat_ior = coat_ior;
    Params->coat_tint = coat_tint;
    Params->coat_intensity = coat_intensity;

    FGlossyClearCoatShader::Exec(GraphBuilder, OutputTexture, *Params);
}
