// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "Shaders/GlossyDualLobe.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "PixelShaderUtils.h"
#include "DataDrivenShaderPlatformInfo.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FGlossyDualLobeShader, "/Plugin/Materialize/GlossyDualLobe.usf", "GlossyDualLobePS", SF_Pixel);

bool FGlossyDualLobeShader::ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
{
    return FDataDrivenShaderPlatformInfo::GetMaxFeatureLevel(Parameters.Platform) >= ERHIFeatureLevel::SM5;
}

void FGlossyDualLobeShader::Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters)
{
    if (!OutputTexture)
    {
        return;
    }

    TShaderMapRef<FGlossyDualLobeShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

    FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
    *PassParameters = Parameters;
    PassParameters->RenderTargets[0] = FRenderTargetBinding(OutputTexture, ERenderTargetLoadAction::ENoAction);

    const FIntRect OutputRect(FIntPoint::ZeroValue, OutputTexture->Desc.Extent);
    FPixelShaderUtils::AddFullscreenPass(
        GraphBuilder,
        GetGlobalShaderMap(GMaxRHIFeatureLevel),
        RDG_EVENT_NAME("Materialize.GlossyDualLobe"),
        PixelShader,
        PassParameters,
        OutputRect);
}

// Helper function to add pass to render graph
void AddPass_GlossyDualLobe(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    FVector3f base_color,
    FVector3f coat_color,
    float energy_conservation
)
{
    if (!OutputTexture)
    {
        return;
    }

    FGlossyDualLobeShader::FParameters* Params = GraphBuilder.AllocParameters<FGlossyDualLobeShader::FParameters>();
    // Bind Scalars
    Params->base_color = base_color;
    Params->coat_color = coat_color;
    Params->energy_conservation = energy_conservation;

    FGlossyDualLobeShader::Exec(GraphBuilder, OutputTexture, *Params);
}
