// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "Shaders/GlossySubsurface.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "PixelShaderUtils.h"
#include "DataDrivenShaderPlatformInfo.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FGlossySubsurfaceShader, "/Plugin/Materialize/GlossySubsurface.usf", "GlossySubsurfacePS", SF_Pixel);

bool FGlossySubsurfaceShader::ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
{
    return FDataDrivenShaderPlatformInfo::GetMaxFeatureLevel(Parameters.Platform) >= ERHIFeatureLevel::SM5;
}

void FGlossySubsurfaceShader::Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters)
{
    if (!OutputTexture)
    {
        return;
    }

    TShaderMapRef<FGlossySubsurfaceShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

    FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
    *PassParameters = Parameters;
    PassParameters->RenderTargets[0] = FRenderTargetBinding(OutputTexture, ERenderTargetLoadAction::ENoAction);

    const FIntRect OutputRect(FIntPoint::ZeroValue, OutputTexture->Desc.Extent);
    FPixelShaderUtils::AddFullscreenPass(
        GraphBuilder,
        GetGlobalShaderMap(GMaxRHIFeatureLevel),
        RDG_EVENT_NAME("Materialize.GlossySubsurface"),
        PixelShader,
        PassParameters,
        OutputRect);
}

// Helper function to add pass to render graph
void AddPass_GlossySubsurface(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    FVector3f sss_color,
    float sss_strength,
    float sss_distortion,
    float sss_power,
    float sss_scale,
    float ambient_strength
)
{
    if (!OutputTexture)
    {
        return;
    }

    FGlossySubsurfaceShader::FParameters* Params = GraphBuilder.AllocParameters<FGlossySubsurfaceShader::FParameters>();
    // Bind Scalars
    Params->sss_color = sss_color;
    Params->sss_strength = sss_strength;
    Params->sss_distortion = sss_distortion;
    Params->sss_power = sss_power;
    Params->sss_scale = sss_scale;
    Params->ambient_strength = ambient_strength;

    FGlossySubsurfaceShader::Exec(GraphBuilder, OutputTexture, *Params);
}
