// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "Shaders/MaterializeSmithVisibility.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "PixelShaderUtils.h"
#include "DataDrivenShaderPlatformInfo.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FMaterializeSmithVisibilityShader, "/Plugin/Materialize/MaterializeSmithVisibility.usf", "MaterializeSmithVisibilityPS", SF_Pixel);

bool FMaterializeSmithVisibilityShader::ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
{
    return FDataDrivenShaderPlatformInfo::GetMaxFeatureLevel(Parameters.Platform) >= ERHIFeatureLevel::SM5;
}

void FMaterializeSmithVisibilityShader::Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters)
{
    if (!OutputTexture)
    {
        return;
    }

    TShaderMapRef<FMaterializeSmithVisibilityShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

    FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
    *PassParameters = Parameters;
    PassParameters->RenderTargets[0] = FRenderTargetBinding(OutputTexture, ERenderTargetLoadAction::ENoAction);

    const FIntRect OutputRect(FIntPoint::ZeroValue, OutputTexture->Desc.Extent);
    FPixelShaderUtils::AddFullscreenPass(
        GraphBuilder,
        GetGlobalShaderMap(GMaxRHIFeatureLevel),
        RDG_EVENT_NAME("Materialize.SmithVisibility"),
        PixelShader,
        PassParameters,
        OutputRect);
}

// Helper function to add pass to render graph
void AddPass_MaterializeSmithVisibility(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture
)
{
    if (!OutputTexture)
    {
        return;
    }

    FMaterializeSmithVisibilityShader::FParameters* Params = GraphBuilder.AllocParameters<FMaterializeSmithVisibilityShader::FParameters>();

    FMaterializeSmithVisibilityShader::Exec(GraphBuilder, OutputTexture, *Params);
}
