// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "Shaders/MaterializeFresnelSchlick.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "PixelShaderUtils.h"
#include "DataDrivenShaderPlatformInfo.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FMaterializeFresnelSchlickShader, "/Plugin/Materialize/MaterializeFresnelSchlick.usf", "MaterializeFresnelSchlickPS", SF_Pixel);

bool FMaterializeFresnelSchlickShader::ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
{
    return FDataDrivenShaderPlatformInfo::GetMaxFeatureLevel(Parameters.Platform) >= ERHIFeatureLevel::SM5;
}

void FMaterializeFresnelSchlickShader::Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters)
{
    if (!OutputTexture)
    {
        return;
    }

    TShaderMapRef<FMaterializeFresnelSchlickShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

    FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
    *PassParameters = Parameters;
    PassParameters->RenderTargets[0] = FRenderTargetBinding(OutputTexture, ERenderTargetLoadAction::ENoAction);

    const FIntRect OutputRect(FIntPoint::ZeroValue, OutputTexture->Desc.Extent);
    FPixelShaderUtils::AddFullscreenPass(
        GraphBuilder,
        GetGlobalShaderMap(GMaxRHIFeatureLevel),
        RDG_EVENT_NAME("Materialize.FresnelSchlick"),
        PixelShader,
        PassParameters,
        OutputRect);
}

// Helper function to add pass to render graph
void AddPass_MaterializeFresnelSchlick(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture
)
{
    if (!OutputTexture)
    {
        return;
    }

    FMaterializeFresnelSchlickShader::FParameters* Params = GraphBuilder.AllocParameters<FMaterializeFresnelSchlickShader::FParameters>();

    FMaterializeFresnelSchlickShader::Exec(GraphBuilder, OutputTexture, *Params);
}
