// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "Shaders/MaterializeGGXDistribution.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "PixelShaderUtils.h"
#include "DataDrivenShaderPlatformInfo.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FMaterializeGGXDistributionShader, "/Plugin/Materialize/MaterializeGGXDistribution.usf", "MaterializeGGXDistributionPS", SF_Pixel);

bool FMaterializeGGXDistributionShader::ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
{
    return FDataDrivenShaderPlatformInfo::GetMaxFeatureLevel(Parameters.Platform) >= ERHIFeatureLevel::SM5;
}

void FMaterializeGGXDistributionShader::Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters)
{
    if (!OutputTexture)
    {
        return;
    }

    TShaderMapRef<FMaterializeGGXDistributionShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

    FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
    *PassParameters = Parameters;
    PassParameters->RenderTargets[0] = FRenderTargetBinding(OutputTexture, ERenderTargetLoadAction::ENoAction);

    const FIntRect OutputRect(FIntPoint::ZeroValue, OutputTexture->Desc.Extent);
    FPixelShaderUtils::AddFullscreenPass(
        GraphBuilder,
        GetGlobalShaderMap(GMaxRHIFeatureLevel),
        RDG_EVENT_NAME("Materialize.GGXDistribution"),
        PixelShader,
        PassParameters,
        OutputRect);
}

// Helper function to add pass to render graph
void AddPass_MaterializeGGXDistribution(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture
)
{
    if (!OutputTexture)
    {
        return;
    }

    FMaterializeGGXDistributionShader::FParameters* Params = GraphBuilder.AllocParameters<FMaterializeGGXDistributionShader::FParameters>();

    FMaterializeGGXDistributionShader::Exec(GraphBuilder, OutputTexture, *Params);
}
