// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "Shaders/MetalAnisotropicSpecular.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "PixelShaderUtils.h"
#include "DataDrivenShaderPlatformInfo.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FMetalAnisotropicSpecularShader, "/Plugin/Materialize/MetalAnisotropicSpecular.usf", "MetalAnisotropicSpecularPS", SF_Pixel);

bool FMetalAnisotropicSpecularShader::ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
{
    return FDataDrivenShaderPlatformInfo::GetMaxFeatureLevel(Parameters.Platform) >= ERHIFeatureLevel::SM5;
}

void FMetalAnisotropicSpecularShader::Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters)
{
    if (!OutputTexture)
    {
        return;
    }

    TShaderMapRef<FMetalAnisotropicSpecularShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

    FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
    *PassParameters = Parameters;
    PassParameters->RenderTargets[0] = FRenderTargetBinding(OutputTexture, ERenderTargetLoadAction::ENoAction);

    const FIntRect OutputRect(FIntPoint::ZeroValue, OutputTexture->Desc.Extent);
    FPixelShaderUtils::AddFullscreenPass(
        GraphBuilder,
        GetGlobalShaderMap(GMaxRHIFeatureLevel),
        RDG_EVENT_NAME("Materialize.MetalAnisotropicSpecular"),
        PixelShader,
        PassParameters,
        OutputRect);
}

// Helper function to add pass to render graph
void AddPass_MetalAnisotropicSpecular(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    float specular_intensity,
    FVector3f specular_tint,
    float anisotropy_direction
)
{
    if (!OutputTexture)
    {
        return;
    }

    FMetalAnisotropicSpecularShader::FParameters* Params = GraphBuilder.AllocParameters<FMetalAnisotropicSpecularShader::FParameters>();
    // Bind Scalars
    Params->specular_intensity = specular_intensity;
    Params->specular_tint = specular_tint;
    Params->anisotropy_direction = anisotropy_direction;

    FMetalAnisotropicSpecularShader::Exec(GraphBuilder, OutputTexture, *Params);
}
