// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "Shaders/MetalFresnelRim.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "PixelShaderUtils.h"
#include "DataDrivenShaderPlatformInfo.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FMetalFresnelRimShader, "/Plugin/Materialize/MetalFresnelRim.usf", "MetalFresnelRimPS", SF_Pixel);

bool FMetalFresnelRimShader::ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
{
    return FDataDrivenShaderPlatformInfo::GetMaxFeatureLevel(Parameters.Platform) >= ERHIFeatureLevel::SM5;
}

void FMetalFresnelRimShader::Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters)
{
    if (!OutputTexture)
    {
        return;
    }

    TShaderMapRef<FMetalFresnelRimShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

    FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
    *PassParameters = Parameters;
    PassParameters->RenderTargets[0] = FRenderTargetBinding(OutputTexture, ERenderTargetLoadAction::ENoAction);

    const FIntRect OutputRect(FIntPoint::ZeroValue, OutputTexture->Desc.Extent);
    FPixelShaderUtils::AddFullscreenPass(
        GraphBuilder,
        GetGlobalShaderMap(GMaxRHIFeatureLevel),
        RDG_EVENT_NAME("Materialize.MetalFresnelRim"),
        PixelShader,
        PassParameters,
        OutputRect);
}

// Helper function to add pass to render graph
void AddPass_MetalFresnelRim(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    float rim_intensity,
    FVector3f rim_color,
    float rim_power,
    float edge_brightness
)
{
    if (!OutputTexture)
    {
        return;
    }

    FMetalFresnelRimShader::FParameters* Params = GraphBuilder.AllocParameters<FMetalFresnelRimShader::FParameters>();
    // Bind Scalars
    Params->rim_intensity = rim_intensity;
    Params->rim_color = rim_color;
    Params->rim_power = rim_power;
    Params->edge_brightness = edge_brightness;

    FMetalFresnelRimShader::Exec(GraphBuilder, OutputTexture, *Params);
}
