// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "Shaders/ToonConfigurableBands.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "PixelShaderUtils.h"
#include "DataDrivenShaderPlatformInfo.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FToonConfigurableBandsShader, "/Plugin/Materialize/ToonConfigurableBands.usf", "ToonConfigurableBandsPS", SF_Pixel);

bool FToonConfigurableBandsShader::ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
{
    return FDataDrivenShaderPlatformInfo::GetMaxFeatureLevel(Parameters.Platform) >= ERHIFeatureLevel::SM5;
}

void FToonConfigurableBandsShader::Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters)
{
    if (!OutputTexture)
    {
        return;
    }

    TShaderMapRef<FToonConfigurableBandsShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

    FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
    *PassParameters = Parameters;
    PassParameters->RenderTargets[0] = FRenderTargetBinding(OutputTexture, ERenderTargetLoadAction::ENoAction);

    const FIntRect OutputRect(FIntPoint::ZeroValue, OutputTexture->Desc.Extent);
    FPixelShaderUtils::AddFullscreenPass(
        GraphBuilder,
        GetGlobalShaderMap(GMaxRHIFeatureLevel),
        RDG_EVENT_NAME("Materialize.ToonConfigurableBands"),
        PixelShader,
        PassParameters,
        OutputRect);
}

// Helper function to add pass to render graph
void AddPass_ToonConfigurableBands(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    float band_count,
    float band_smoothness,
    float custom_bands
)
{
    if (!OutputTexture)
    {
        return;
    }

    FToonConfigurableBandsShader::FParameters* Params = GraphBuilder.AllocParameters<FToonConfigurableBandsShader::FParameters>();
    // Bind Scalars
    Params->band_count = band_count;
    Params->band_smoothness = band_smoothness;
    Params->custom_bands = custom_bands;

    FToonConfigurableBandsShader::Exec(GraphBuilder, OutputTexture, *Params);
}
