// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "Shaders/ToonCelShading.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "PixelShaderUtils.h"
#include "DataDrivenShaderPlatformInfo.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FToonCelShadingShader, "/Plugin/Materialize/ToonCelShading.usf", "ToonCelShadingPS", SF_Pixel);

bool FToonCelShadingShader::ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
{
    return FDataDrivenShaderPlatformInfo::GetMaxFeatureLevel(Parameters.Platform) >= ERHIFeatureLevel::SM5;
}

void FToonCelShadingShader::Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters)
{
    if (!OutputTexture)
    {
        return;
    }

    TShaderMapRef<FToonCelShadingShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

    FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
    *PassParameters = Parameters;
    PassParameters->RenderTargets[0] = FRenderTargetBinding(OutputTexture, ERenderTargetLoadAction::ENoAction);

    const FIntRect OutputRect(FIntPoint::ZeroValue, OutputTexture->Desc.Extent);
    FPixelShaderUtils::AddFullscreenPass(
        GraphBuilder,
        GetGlobalShaderMap(GMaxRHIFeatureLevel),
        RDG_EVENT_NAME("Materialize.ToonCelShading"),
        PixelShader,
        PassParameters,
        OutputRect);
}

// Helper function to add pass to render graph
void AddPass_ToonCelShading(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    FVector3f shadow_color,
    FVector3f highlight_color,
    FVector3f midtone_color,
    float band_count,
    float band_smoothness,
    float wrap_amount
)
{
    if (!OutputTexture)
    {
        return;
    }

    FToonCelShadingShader::FParameters* Params = GraphBuilder.AllocParameters<FToonCelShadingShader::FParameters>();
    // Bind Scalars
    Params->shadow_color = shadow_color;
    Params->highlight_color = highlight_color;
    Params->midtone_color = midtone_color;
    Params->band_count = band_count;
    Params->band_smoothness = band_smoothness;
    Params->wrap_amount = wrap_amount;

    FToonCelShadingShader::Exec(GraphBuilder, OutputTexture, *Params);
}
