// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "Shaders/ToonRimLight.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "PixelShaderUtils.h"
#include "DataDrivenShaderPlatformInfo.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FToonRimLightShader, "/Plugin/Materialize/ToonRimLight.usf", "ToonRimLightPS", SF_Pixel);

bool FToonRimLightShader::ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
{
    return FDataDrivenShaderPlatformInfo::GetMaxFeatureLevel(Parameters.Platform) >= ERHIFeatureLevel::SM5;
}

void FToonRimLightShader::Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters)
{
    if (!OutputTexture)
    {
        return;
    }

    TShaderMapRef<FToonRimLightShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

    FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
    *PassParameters = Parameters;
    PassParameters->RenderTargets[0] = FRenderTargetBinding(OutputTexture, ERenderTargetLoadAction::ENoAction);

    const FIntRect OutputRect(FIntPoint::ZeroValue, OutputTexture->Desc.Extent);
    FPixelShaderUtils::AddFullscreenPass(
        GraphBuilder,
        GetGlobalShaderMap(GMaxRHIFeatureLevel),
        RDG_EVENT_NAME("Materialize.ToonRimLight"),
        PixelShader,
        PassParameters,
        OutputRect);
}

// Helper function to add pass to render graph
void AddPass_ToonRimLight(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    FVector3f rim_color,
    float rim_power,
    float rim_intensity,
    float rim_threshold,
    float rim_smoothness
)
{
    if (!OutputTexture)
    {
        return;
    }

    FToonRimLightShader::FParameters* Params = GraphBuilder.AllocParameters<FToonRimLightShader::FParameters>();
    // Bind Scalars
    Params->rim_color = rim_color;
    Params->rim_power = rim_power;
    Params->rim_intensity = rim_intensity;
    Params->rim_threshold = rim_threshold;
    Params->rim_smoothness = rim_smoothness;

    FToonRimLightShader::Exec(GraphBuilder, OutputTexture, *Params);
}
