// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "Shaders/ToonOutlineDetection.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "PixelShaderUtils.h"
#include "DataDrivenShaderPlatformInfo.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FToonOutlineDetectionShader, "/Plugin/Materialize/ToonOutlineDetection.usf", "ToonOutlineDetectionPS", SF_Pixel);

bool FToonOutlineDetectionShader::ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
{
    return FDataDrivenShaderPlatformInfo::GetMaxFeatureLevel(Parameters.Platform) >= ERHIFeatureLevel::SM5;
}

void FToonOutlineDetectionShader::Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters)
{
    if (!OutputTexture)
    {
        return;
    }

    TShaderMapRef<FToonOutlineDetectionShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

    FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
    *PassParameters = Parameters;
    PassParameters->RenderTargets[0] = FRenderTargetBinding(OutputTexture, ERenderTargetLoadAction::ENoAction);

    const FIntRect OutputRect(FIntPoint::ZeroValue, OutputTexture->Desc.Extent);
    FPixelShaderUtils::AddFullscreenPass(
        GraphBuilder,
        GetGlobalShaderMap(GMaxRHIFeatureLevel),
        RDG_EVENT_NAME("Materialize.ToonOutlineDetection"),
        PixelShader,
        PassParameters,
        OutputRect);
}

// Helper function to add pass to render graph
void AddPass_ToonOutlineDetection(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    FVector3f outline_color,
    float outline_thickness,
    float depth_threshold,
    float normal_threshold,
    float depth_weight,
    float normal_weight
)
{
    if (!OutputTexture)
    {
        return;
    }

    FToonOutlineDetectionShader::FParameters* Params = GraphBuilder.AllocParameters<FToonOutlineDetectionShader::FParameters>();
    // Bind Scalars
    Params->outline_color = outline_color;
    Params->outline_thickness = outline_thickness;
    Params->depth_threshold = depth_threshold;
    Params->normal_threshold = normal_threshold;
    Params->depth_weight = depth_weight;
    Params->normal_weight = normal_weight;

    FToonOutlineDetectionShader::Exec(GraphBuilder, OutputTexture, *Params);
}
