// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FGlossySubsurfaceShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FGlossySubsurfaceShader);
    SHADER_USE_PARAMETER_STRUCT(FGlossySubsurfaceShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(FVector3f, sss_color)
        SHADER_PARAMETER(float, sss_strength)
        SHADER_PARAMETER(float, sss_distortion)
        SHADER_PARAMETER(float, sss_power)
        SHADER_PARAMETER(float, sss_scale)
        SHADER_PARAMETER(float, ambient_strength)
        RENDER_TARGET_BINDING_SLOTS()
    END_SHADER_PARAMETER_STRUCT()

    static bool ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters);
    static void Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters);
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FGlossySubsurfaceShader, "/Plugin/Materialize/GlossySubsurface.usf", "GlossySubsurfacePS", SF_Pixel);

// Helper function to add pass to render graph
void AddPass_GlossySubsurface(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    FVector3f sss_color,
    float sss_strength,
    float sss_distortion,
    float sss_power,
    float sss_scale,
    float ambient_strength
);
