// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FGlossyClearCoatShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FGlossyClearCoatShader);
    SHADER_USE_PARAMETER_STRUCT(FGlossyClearCoatShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(float, coat_ior)
        SHADER_PARAMETER(FVector3f, coat_tint)
        SHADER_PARAMETER(float, coat_intensity)
        RENDER_TARGET_BINDING_SLOTS()
    END_SHADER_PARAMETER_STRUCT()

    static bool ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters);
    static void Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters);
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FGlossyClearCoatShader, "/Plugin/Materialize/GlossyClearCoat.usf", "GlossyClearCoatPS", SF_Pixel);

// Helper function to add pass to render graph
void AddPass_GlossyClearCoat(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    float coat_ior,
    FVector3f coat_tint,
    float coat_intensity
);
