// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FGlossyDualLobeShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FGlossyDualLobeShader);
    SHADER_USE_PARAMETER_STRUCT(FGlossyDualLobeShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(FVector3f, base_color)
        SHADER_PARAMETER(FVector3f, coat_color)
        SHADER_PARAMETER(float, energy_conservation)
        RENDER_TARGET_BINDING_SLOTS()
    END_SHADER_PARAMETER_STRUCT()

    static bool ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters);
    static void Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters);
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FGlossyDualLobeShader, "/Plugin/Materialize/GlossyDualLobe.usf", "GlossyDualLobePS", SF_Pixel);

// Helper function to add pass to render graph
void AddPass_GlossyDualLobe(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    FVector3f base_color,
    FVector3f coat_color,
    float energy_conservation
);
