// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FMetalAnisotropicSpecularShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FMetalAnisotropicSpecularShader);
    SHADER_USE_PARAMETER_STRUCT(FMetalAnisotropicSpecularShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(float, specular_intensity)
        SHADER_PARAMETER(FVector3f, specular_tint)
        SHADER_PARAMETER(float, anisotropy_direction)
        RENDER_TARGET_BINDING_SLOTS()
    END_SHADER_PARAMETER_STRUCT()

    static bool ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters);

    // Execute as a fullscreen RDG pixel pass into OutputTexture.
    static void Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters);
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FMetalAnisotropicSpecularShader, "/Plugin/Materialize/MetalAnisotropicSpecular.usf", "MetalAnisotropicSpecularPS", SF_Pixel);

// Helper function to add pass to render graph
void AddPass_MetalAnisotropicSpecular(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    float specular_intensity,
    FVector3f specular_tint,
    float anisotropy_direction
);
