// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FMetalFresnelRimShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FMetalFresnelRimShader);
    SHADER_USE_PARAMETER_STRUCT(FMetalFresnelRimShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(float, rim_intensity)
        SHADER_PARAMETER(FVector3f, rim_color)
        SHADER_PARAMETER(float, rim_power)
        SHADER_PARAMETER(float, edge_brightness)
        RENDER_TARGET_BINDING_SLOTS()
    END_SHADER_PARAMETER_STRUCT()

    static bool ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters);
    static void Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters);
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FMetalFresnelRimShader, "/Plugin/Materialize/MetalFresnelRim.usf", "MetalFresnelRimPS", SF_Pixel);

// Helper function to add pass to render graph
void AddPass_MetalFresnelRim(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    float rim_intensity,
    FVector3f rim_color,
    float rim_power,
    float edge_brightness
);
