// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FToonCelShadingShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FToonCelShadingShader);
    SHADER_USE_PARAMETER_STRUCT(FToonCelShadingShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(FVector3f, shadow_color)
        SHADER_PARAMETER(FVector3f, highlight_color)
        SHADER_PARAMETER(FVector3f, midtone_color)
        SHADER_PARAMETER(float, band_count)
        SHADER_PARAMETER(float, band_smoothness)
        SHADER_PARAMETER(float, wrap_amount)
        RENDER_TARGET_BINDING_SLOTS()
    END_SHADER_PARAMETER_STRUCT()

    static bool ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters);
    static void Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters);
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FToonCelShadingShader, "/Plugin/Materialize/ToonCelShading.usf", "ToonCelShadingPS", SF_Pixel);

// Helper function to add pass to render graph
void AddPass_ToonCelShading(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    FVector3f shadow_color,
    FVector3f highlight_color,
    FVector3f midtone_color,
    float band_count,
    float band_smoothness,
    float wrap_amount
);
