// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FToonOutlineDetectionShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FToonOutlineDetectionShader);
    SHADER_USE_PARAMETER_STRUCT(FToonOutlineDetectionShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(FVector3f, outline_color)
        SHADER_PARAMETER(float, outline_thickness)
        SHADER_PARAMETER(float, depth_threshold)
        SHADER_PARAMETER(float, normal_threshold)
        SHADER_PARAMETER(float, depth_weight)
        SHADER_PARAMETER(float, normal_weight)
        RENDER_TARGET_BINDING_SLOTS()
    END_SHADER_PARAMETER_STRUCT()

    static bool ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters);
    static void Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters);
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FToonOutlineDetectionShader, "/Plugin/Materialize/ToonOutlineDetection.usf", "ToonOutlineDetectionPS", SF_Pixel);

// Helper function to add pass to render graph
void AddPass_ToonOutlineDetection(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    FVector3f outline_color,
    float outline_thickness,
    float depth_threshold,
    float normal_threshold,
    float depth_weight,
    float normal_weight
);
