// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FToonSpecularShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FToonSpecularShader);
    SHADER_USE_PARAMETER_STRUCT(FToonSpecularShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(FVector3f, specular_color)
        SHADER_PARAMETER(float, specular_size)
        SHADER_PARAMETER(float, specular_steps)
        SHADER_PARAMETER(float, specular_intensity)
        RENDER_TARGET_BINDING_SLOTS()
    END_SHADER_PARAMETER_STRUCT()

    static bool ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters);
    static void Exec(FRDGBuilder& GraphBuilder, FRDGTextureRef OutputTexture, const FParameters& Parameters);
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FToonSpecularShader, "/Plugin/Materialize/ToonSpecular.usf", "ToonSpecularPS", SF_Pixel);

// Helper function to add pass to render graph
void AddPass_ToonSpecular(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef OutputTexture,
    FVector3f specular_color,
    float specular_size,
    float specular_steps,
    float specular_intensity
);
